<?php

use Drupal\labl_blocks\Storybook\StoryDiscovery;

/**
 * Implements hook_theme().
 */
function labl_blocks_theme($existing, $type, $theme, $path) {
  $discovery = new StoryDiscovery();
  $definitions = [];
  foreach ($discovery->discover() as $story) {
    $variables = [];
    foreach ($story['fields'] as $field) {
      $variables[$field['name']] = $field['default'];
    }

    $definitions[$story['id']] = [
      'variables' => $variables,
      'template' => $story['template'],
      'path' => $story['path'],
    ];
  }

  return $definitions;
}
